// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Builds a valid Postgres URL for Prisma CLI (`db execute`, `db pull`).
 * Special characters in passwords (? @ # $ etc.) break a single URI string; use
 * SUPABASE_DB_* vars so we can encode them with encodeURIComponent.
 */
function prismaDatasourceUrl(): string {
  const host = process.env.SUPABASE_DB_HOST?.trim();
  const user = process.env.SUPABASE_DB_USER?.trim() ?? "postgres";
  const password = process.env.SUPABASE_DB_PASSWORD;
  const port = process.env.SUPABASE_DB_PORT?.trim() ?? "5432";
  const database = process.env.SUPABASE_DB_NAME?.trim() ?? "postgres";

  if (host && password) {
    const u = encodeURIComponent(user);
    const p = encodeURIComponent(password);
    return `postgresql://${u}:${p}@${host}:${port}/${database}?sslmode=require`;
  }

  const direct = process.env.DIRECT_URL?.trim();
  const pooled = process.env.DATABASE_URL?.trim();
  return direct || pooled || "";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: prismaDatasourceUrl(),
  },
});
